server:
    port: 8080
    tomcat:
      uri-encoding: UTF-8
    compression:
      enabled: true
      mime-types: application/json, application/xml

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://lbadb:5432/lba?currentSchema=teams
    username: lba
    password: lb4Us3r
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          default_schema: teams
          temp:
            use_jdbc_metadata_defaults: false
    flyway:
      enabled: true
      schemas: ${spring.jpa.properties.hibernate.default_schema}
      table: flyway_schema_version
    http:
      multipart:
        enabled: true


logging:
  file: ${java.io.tmpdir}/${spring.application.name}.log
  level:
    root: info
